"""
setting all necessary parameters and key bindings
"""
SCREEN_HEIGHT = 200 * 4
SCREEN_WIDTH = 300 * 4
NUMBER_OF_RAYS = 100
LEVEL_SCREEN_MARGIN_TOP = 0
LEVEL_SCREEN_MARGIN_BOTTOM = 0
LEVEL_SCREEN_MARGIN_LEFT = 0
LEVEL_SCREEN_MARGIN_RIGHT = 0
RENDER_TEXTURES = True
MAX_FOV_DEGREES = 90
MIN_FOV_DEGREES = 45
CEILING_COLOR_RGB = (47, 47, 47)
FLOOR_COLOR_RGB = (117, 115, 116)
HORIZONTAL_WALL_COLOR_RGB = (255, 0, 0)
VERTICAL_WALL_COLOR_RGB = (200, 0, 0)
MS_PER_FRAME = 16
DOOR_INDEX = 5

# Hotkeys
KEY_MOVE_UP = 'w'
KEY_MOVE_DOWN = 's'
KEY_MOVE_LEFT = 'a'
KEY_MOVE_RIGHT = 'd'
KEY_ROTATE_LEFT1 = 'Left'
KEY_ROTATE_RIGHT1 = 'Right'
KEY_ROTATE_LEFT2 = 'q'
KEY_ROTATE_RIGHT2 = 'e'
KEY_ZOOM_IN = 'plus'
KEY_ZOOM_OUT = 'minus'
KEY_WEAPON_1 = '1'
KEY_WEAPON_2 = '2'
KEY_WEAPON_3 = '3'


